public abstract class Automobil implements Fahrzeug {
    protected int anzahlSitze;
    protected String kennzeichen;

    protected int anzahlRaeder;

    public Automobil() {
    }

    public Automobil(int anzahlSitze, String kennzeichen, int anzahlRaeder) {

        this.anzahlSitze = anzahlSitze;
        this.kennzeichen = kennzeichen;
        this.anzahlRaeder = anzahlRaeder;
    }
    @Override
    public int getAnzahlSitze() {
        return this.anzahlSitze;
    }

    @Override
    public void setAnzahlSitze(int anzahlSitze) {
        this.anzahlSitze = anzahlSitze;
    }

    @Override
    public String getKennzeichen() {
        return this.kennzeichen;
    }

    @Override
    public void setKennzeichen(String kennzeichen) {
        this.kennzeichen = kennzeichen;
    }

    public int getAnzahlRaeder() {
        return this.anzahlRaeder;
    }

    public void setAnzahlRaeder(int anzahlRaeder) {
        this.anzahlRaeder = anzahlRaeder;
    }



    // auto generated stuff by vs code extension

    // public Automobil anzahlSitze(int anzahlSitze) {
    //     this.anzahlSitze = anzahlSitze;
    //     return this;
    // }

    // public Automobil kennzeichen(String kennzeichen) {
    //     this.kennzeichen = kennzeichen;
    //     return this;
    // }

    // public Automobil anzahlRaeder(int anzahlRaeder) {
    //     this.anzahlRaeder = anzahlRaeder;
    //     return this;
    // }





    // auto generated by vs-code extension

    // @Override
    // public boolean equals(Object o) {
    //     if (o == this)
    //         return true;
    //     if (!(o instanceof Automobil)) {
    //         return false;
    //     }
    //     Automobil automobil = (Automobil) o;
    //     return anzahlSitze == automobil.anzahlSitze && Objects.equals(kennzeichen, automobil.kennzeichen) && anzahlRaeder == automobil.anzahlRaeder;
    // }

    // @Override
    // public int hashCode() {
    //     return Objects.hash(anzahlSitze, kennzeichen, anzahlRaeder);
    // }

    // @Override
    // public String toString() {
    //     return "{" +
    //         " anzahlSitze='" + getAnzahlSitze() + "'" +
    //         ", kennzeichen='" + getKennzeichen() + "'" +
    //         ", anzahlRaeder='" + getAnzahlRaeder() + "'" +
    //         "}";
    // }

       
}